apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/jehoon0908-ops/myapp:sha-b92477987bdafd2e8ac2bb609929d473907d97aa
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
