apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/jehoon0908-ops/myapp:sha-09d0d9db5b07871c870bf63f83c41d504bc31722
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
