apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 10.10.20.220:30002/myapp/myapp:sha-96b86b134e2414d17c35db9438eb4eee9d3e2097
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
